# -*- coding: utf-8 -*-
"""
/***************************************************************************
 StyleImport
                                 A QGIS plugin
 Importer style
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-05-17
        copyright            : (C) 2022 by Romain Lagrange
        email                : romain.lagrange@pceservices.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load StyleImport class from file StyleImport.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .import_style import StyleImport
    return StyleImport(iface)
